import jsPDF from 'jspdf';
import 'jspdf-autotable'; 

export const employeeDetailsPDF = (officeId, employees) => {
  const doc = new jsPDF();

 
  const currentDate = new Date().toLocaleDateString();

  
  doc.setFontSize(18);
  doc.text('Employee Details Report', 14, 20);

 
  doc.setFontSize(12);
  doc.text(`Date: ${currentDate}`, 14, 30);
  doc.text(`Generated By: Office ID ${officeId}`, 14, 40);

 
  const head = [['Employee ID', 'Employee Name', 'Designation', 'Email']];

  
  const body = employees.map(emp => [
    emp.employeeId,
    emp.employeeName,
    emp.employeeDesignation,
    emp.email,
  ]);

 
  doc.autoTable({
    startY: 50,
    head,
    body,
    theme: 'grid',  
    headStyles: {
      fillColor: [41, 128, 185],  // Blue header color
      textColor: [255, 255, 255],  // White text
    },
    bodyStyles: {
      fillColor: [245, 245, 245],  // Light gray row background
      textColor: [0, 0, 0],  // Black text color
    },
    alternateRowStyles: {
      fillColor: [255, 255, 255],  // White background for alternating rows
    },
    margin: { top: 50 },
  });

  // Save the PDF
  doc.save(`Employee_Details_Report_${officeId}.pdf`);
};
