import jsPDF from 'jspdf';
import 'jspdf-autotable'; // Import for table formatting

export const individualReportPDF = (officeId, applications,officeName,employeeId,employeeName) => {
  const doc = new jsPDF();
  
  
  const currentDate = new Date().toLocaleDateString();
  
  
  doc.setFontSize(18);
  doc.text('Individual Application Report', 14, 20);
  
 
  doc.setFontSize(12);
  doc.text(`Date: ${currentDate}`, 14, 30);
  doc.text(`Generated By: ${officeId} - ${officeName}`, 14, 40);
  doc.text(`Employee : ${employeeId} - ${employeeName}`, 14, 50);
  
  // Define starting point for content
  let startY = 60;

  
  applications.forEach((applicationData, index) => {
    
    doc.setFontSize(14);
    doc.text(`Application ${index + 1}:`, 14, startY);
    
    
    const details = [
      ['Application Number', applicationData.ApplicationNumber || 'N/A'],
      ['Number of Days', applicationData.NoOfDays || 'N/A'],
      ['Created At', applicationData.created_at ? new Date(applicationData.created_at).toLocaleString() : 'N/A'],
      ['Status', applicationData.status || 'N/A']
    ];
    
    
    doc.autoTable({
      startY: startY + 10,
      head: [['Field', 'Value']],
      body: details,
      theme: 'grid',  // Grid layout for cleaner look
      headStyles: {
        fillColor: [41, 128, 185],  // Blue header color
        textColor: [255, 255, 255],  // White text
      },
      bodyStyles: {
        fillColor: [245, 245, 245],  // Light gray row background
        textColor: [0, 0, 0],  // Black text color
      },
      margin: { top: 10 },
    });
    
   
    startY = doc.autoTable.previous.finalY + 20;
  });

  
  doc.save(`Individual_Application_Report_Office_${officeId}.pdf`);
};
