import jsPDF from 'jspdf';
import 'jspdf-autotable'; 

export const officeReportPDF = (officeId, responseData) => {
  const doc = new jsPDF();

 
  const currentDate = new Date().toLocaleDateString();


  doc.setFontSize(18);
  doc.text('Office Report', 14, 20);

 
  doc.setFontSize(12);
  doc.text(`Date: ${currentDate}`, 14, 30);
  doc.text(`Generated By: ${officeId}`, 14, 40);

  
  const openedCount = responseData.filter(item => item.applicationStatus === 'opened').length;
  const rejectedCount = responseData.filter(item => item.applicationStatus === 'rejected').length;

  doc.setFontSize(12);
  doc.text('Summary:', 14, 50);
  doc.autoTable({
    startY: 55,
    head: [['Total Applications', 'Opened Applications', 'Rejected Applications']],
    body: [[responseData.length, openedCount, rejectedCount]],
  });

  
  doc.text('Detailed Application Report:', 14, doc.autoTable.previous.finalY + 10);
  
  responseData.forEach((app, index) => {
    doc.setFontSize(10);
    doc.text(`Application ${index + 1}:`, 14, doc.autoTable.previous.finalY + 20);

    const body = [
      ['Applicant Name', app.applicantName],
      ['Application Number', app.applicationNumber],
      ['Application Name', app.applicationName],
      ['Application Date', app.applicationDate],
      ['Application Status', app.applicationStatus],
      ['Application Type ID', app.applicationTypeId],
      ['Office ID', app.officeId],
      ['Email Address', app.applicantMail],
      ['Mobile Number', app.applicantMobileNumber],
      ['Applicant Address', app.applicantAddress]
    ];

    doc.autoTable({
      startY: doc.autoTable.previous.finalY + 25,
      body,
      theme: 'grid',  
    });
  });

  
  doc.save(`Office_Report_${officeId}.pdf`);
};
